### PR TITLE
Update LICENSE

### PR DESCRIPTION
**Pull request by jtrudell**

### CODE REVIEW

**Comment by jtrudell** [comment]
@dinkengraven you are missing a great opportunity to revise the MIT license.

**Comment by dinkengraven** [comment]
@jtrudell oh hell yes i'm gonna license the hell out of this

**Comment by jtrudell** [comment]
This is what Ben and I were laughing at today when you asked if we were
laughing at you. Now we are laughing WITH you.

On Wed, Oct 14, 2015 at 10:26 PM, Katelyn Dinkgrave <
notifications@github.com> wrote:

> @jtrudell https://github.com/jtrudell oh hell yes i'm gonna license the
> hell out of this
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/dinkengraven/knope/pull/1#issuecomment-148271515.

## 

312-218-6381 (cell)
jtrudell78 (skype)
jtrudell@gmail.com

**Comment by dinkengraven** [comment]
well it's beautiful and i love it.

**Comment by jtrudell** [comment]
👊🏼

Jen

jtrudell@gmail.com 
312-218-6381 (cell)
jtrudell78 (Skype)

**Pull request merged**
